
select
    staff_id,
    staff_first_name,
    staff_last_name,
    staff_email,
    staff_phone,
    staff_active,
    manager_id,
    manager_first_name,
    manager_last_name,
    store_id, 
    store_name,
    store_state,
    store_city,
    store_zip_code,
    order_date,
    customer_id,
    customer_first_name, 
    customer_last_name, 
    customer_phone, 
    customer_email, 
    customer_city, 
    customer_state, 
    customer_zip_code,
    ROUND(SUM(net_sales_amount), 2) AS total_net_store_amount, 
    ROUND(SUM(gross_sales_amount), 2) AS total_gross_store_amount,
    ROUND(SUM(discount_amount), 2) AS total_discount_store_amount, 
    ROUND(SUM(net_sales_amount) / SUM(SUM(net_sales_amount)) OVER (PARTITION BY store_id), 4) AS sales_contribution_per_staff_ratio
from  {{ ref('int_localbike__stores_performance') }}
GROUP BY 
    staff_id,
    staff_first_name,
    staff_last_name,
    staff_email,
    staff_phone,
    staff_active,
    manager_id,
    manager_first_name,
    manager_last_name,
    store_id, 
    store_name,
    store_state,
    store_city,
    store_zip_code,
    order_date, 
    customer_id,
    customer_first_name, 
    customer_last_name, 
    customer_phone, 
    customer_email, 
    customer_city, 
    customer_state, 
    customer_zip_code