
select
    staff_id,
    staff_first_name,
    staff_last_name,
    staff_email,
    staff_phone,
    staff_active,
    manager_id,
    manager_first_name,
    manager_last_name,
    store_id, 
    store_name,
    store_state,
    store_city,
    store_zip_code,
    order_date,
    ROUND(SUM(net_sales_amount), 2) AS total_net_store_amount
from  {{ ref('int_localbike__stores_staffs_performance') }}
GROUP BY 
    staff_id,
    staff_first_name,
    staff_last_name,
    staff_email,
    staff_phone,
    staff_active,
    manager_id,
    manager_first_name,
    manager_last_name,
    store_id, 
    store_name,
    store_state,
    store_city,
    store_zip_code,
    order_date